### ISSUE TITLE
question: Is there any way to pass the auth_pass value to Redis?

### ISSUE THREAD

**Issue by angelxmoreno** [Vinelab/node-promise-cache#1]

**Comment by Mulkave** [comment]
Yes you may pass a custom configuration to Redis as follows:

``` coffeescript
Cache = require('promise-cache').create({
    redis:
        host: '127.0.0.1',
        port: 6379
        pool: {max: 1, min: 1}
})
```

**Comment by angelxmoreno** [comment]
Your example does not show any indication on how or where the auth_pass property can be passed to promise-cache. Please show an example. Please re-open.

**Comment by Mulkave** [comment]
@angelxmoreno oops my bad, just checked with the code again and appears to not be supported, though easy to add. Here: https://github.com/Vinelab/node-promise-cache/blob/master/lib/stores/RedisStore.coffee#L162

all that is needed is to update the following with `auth_pass` and make sure it's in the default config. Sorry no time on my hands to code this and test/release so a PR is much appreciated.

``` coffeescript
    pool = new RedisPool({
        host: config.redis.host
        port: config.redis.port
        auth_pass: config.redis.auth_pass
    }, {
        max: config.redis.pool.max
        min: config.redis.pool.minutes
    })
```

Also feel free to add all the config settings supported by https://github.com/joshuah/sol-redis-pool

**Comment by angelxmoreno** [comment]
Nice, I'll work on it

**Comment by Mulkave** [comment]
@angelxmoreno cool awaiting your PR :smile:
